image: node:latest

stages:
  - npm
  - test
  - cleanup

cache:
  paths:
    - node_modules/

npm:
  stage: npm

  tags:
    - docker

  script:
    - npm cache clean --force
    - npm install

test:
  stage: test

  tags:
    - docker

  script:
    - echo No tests to run

cleanup:
  stage: cleanup

  script:
    - echo "Cleaning up"
    - rm -rf "%CACHE_PATH%/%CI_PIPELINE_ID%"

  when: always
